[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.58.3"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://tender-kirch-3ac47b.netlify.app/"